### ISSUE TITLE
Bug: Black screen on Linux

### ISSUE THREAD

**Issue by cgmcintyr** [theWebby/YoutubeMySpotify#5]
When running the AppImage on linux I get a black screen. The following error is printed on the console:

``` 
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

**Comment by cgmcintyr** [comment]
I'm running the `YoutubeMySpotify - First Stable Release (0.1.0)` release

**Comment by theWebby** [comment]
Closing this you problem.

**Comment by cgmcintyr** [comment]
Yeah, to confirm this issue resolved after a restart... V strange

**Comment by theWebby** [comment]
Strange? I'd say that's pretty standard for ubuntu.
